#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page.
sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i sed -i "/etc/nginx/sites-enabled/default"

sudo service nginx restart
